"""
Django settings for renti project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

# Load .env file
load_dotenv()

# Africa's Talking credentials and configuration.  ``SHORTCODE`` was being
# overloaded in the .env file; the value actually corresponds to the USSD
# service code (e.g. ``*123#``).  Reserve ``SERVICE_CODE`` for that purpose
# and introduce a separate variable for the SMS sender ID.
# Africa's Talking configuration.  We support separate sandbox and
# production credentials; production variables have the plain name while
# sandbox values are suffixed with ``_SANDBOX``.  During development the
# sandbox keys are usually populated, and the code will transparently
# fall back to them if no live value is available.  When deploying to a
# live environment you can set the non-sandbox variables to your real
# credentials and omit the suffix entirely.

# credentials
AFRICAS_TALKING_USERNAME = (
    os.getenv("AFRICAS_TALKING_USERNAME")
    or os.getenv("AFRICAS_TALKING_USERNAME_SANDBOX")
)
AFRICAS_TALKING_API_KEY = (
    os.getenv("AFRICAS_TALKING_API_KEY")
    or os.getenv("AFRICAS_TALKING_API_KEY_SANDBOX")
)

# service code used by the USSD gateway to identify this application
AFRICAS_TALKING_SERVICE_CODE = (
    os.getenv("AFRICAS_TALKING_SERVICE_CODE")
    or os.getenv("AFRICAS_TALKING_SERVICE_CODE_SANDBOX")
)

# shortcode/sender ID to use when sending SMS messages via the AT SMS
# service.  The sandbox value may differ from your production sender.
AFRICAS_TALKING_SMS_SHORTCODE = (
    os.getenv("AFRICAS_TALKING_SMS_SHORTCODE")
    or os.getenv("AFRICAS_TALKING_SMS_SHORTCODE_SANDBOX")
)

# callback URL used by AT to notify us of USSD sessions; often set
# automatically by the sandbox dashboard and normally the same value for
# both environments but we allow overriding individually.
AFRICAS_TALKING_CALLBACK_URL = (
    os.getenv("AFRICAS_TALKING_CALLBACK_URL")
    or os.getenv("AFRICAS_TALKING_CALLBACK_URL_SANDBOX")
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c)f1sxb^crn78se(j*e$s0#-%mpfv@^5dyp)io$m&^!6jok9=9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'properties',
    'tenants',
    'payments',
    'maintenance',
    'communications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'renti.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'renti.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Basic logging configuration so view logger messages are visible during development
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(asctime)s %(name)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'communications': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
